version: "3"
services:
  zigcloud:
    image: opsdocker.ziggurat.cn/dashboard/zigcloud
    container_name: zigcloud
    restart: always
    environment:
      - ALICLOUD_REGION_ID=cn-huhehaote
      - ALICLOUD_ACCESS_KEY_ID=LTAIP5a8969b3WUho
      - ALICLOUD_ACCESS_KEY_SECRET=R94ZD14r8kfZlEZuk69mclpppxKSoCc
      - ALICLOUD_SNAPSHOT_IMAGE_ID=m-hp394odccetza0zc88cc
    volumes:
      - logs:/go/src/zig-cloud/logs
      - database/zigcloud.db:/go/src/zig-cloud/zigcloud.db
    ports:
      - "8080:8080"

volumes:
  logs: {}
  database: {}
